### ISSUE TITLE
cmd close after download

### ISSUE THREAD

**Issue by IceSaffroN** [baobabKoodaa/one-click-youtube-dl#1]
Is there anyway to have the cmd close after the download has finished? Thanks.

**Comment by baobabKoodaa** [comment]
Hi IceSaffroN! I created a new release for you with support for `--closeprompt` parameter. Note that this will also close the command prompt in case of errors, so using this parameter will have the unfortunate effect of hiding errors. You can take this into use by downloading the latest release and appending the parameter to the `.bat` file.

**Comment by IceSaffroN** [comment]
Hi baobabKoodaa, Thanks for the quick response. I just gave it a go and it works perfectly! Thanks so much!
