### ISSUE TITLE
OneClick No Longer Working

### ISSUE THREAD

**Issue by fatmagic** [baobabKoodaa/one-click-youtube-dl#2]
Hey Boabab,

OneClick doesn't work anymore I think because YouTubeDL isn't working any longer. I am now using yt-dlp which is forked from the original work (I believe). Is there any chance you'll update One-Click to work with yt-dlp? I love One-Click, it's been so useful for me.

Hope you can make it work - but I understand if you don't have time.

Thanks!

**Comment by baobabKoodaa** [comment]
Hey, I have also been using yt-dlp for a long time now. I simply renamed the portable executable `yt-dlp.exe` to `youtube-dl.exe` in the folder where the one click files are. Try to do the same and let me know if you have problems.

**Comment by fatmagic** [comment]
Ah I'm an idiot and should have thought of that... so easy to fix. Sorry to bug you, I will try this now :)

EDIT: it works! Thank you
